### ISSUE TITLE
Connection to host

### ISSUE THREAD

**Issue by FroimT** [memgraph/pymgclient#36]
Hi, I am trying to connect to the host as in the given example. However, I get the error below.
Could it be that the firewall is blocking it? Which programs need to be allowed to pass?

OperationalError                          Traceback (most recent call last)
Input In [10], in <cell line: 1>()
----> 1 conn = mgclient.connect(host='127.0.0.1', port=7687)

OperationalError: couldn't connect to host: Connection refused.

**Comment by g-despot** [comment]
Did you make sure that Memgraph is up and running before trying to create the connection?
Also, did you try checking the log files in Memgraph? [Here is a guide](https://memgraph.com/docs/memgraph/how-to-guides/config-logs) on where you can find them.

**Comment by FroimT** [comment]
Ok, thanks. I thought memegraph would be launched when I do the gqlalechmy import.
